name: Makedo Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Build makedo
      run: |
        cd src
        go mod tidy
        go build -ldflags "-X main.versionString=$(cat ../VERSION)" -o ../bin/makedo
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Run Markdown Tests
      run: ./mktest.sh
